version: 0.0

containers:
  main:
    phases:
      pre_build:
        commands:
          - echo 'Inside Node.js Source Directory'
          - npm install unit.js
          - npm install -g mocha
      during_build:
        commands:
          - echo 'Compiling the Node.js Code'
          - mocha HelloWorld.js
      post_build:
        commands:
          - echo "Would deploy here"
    artifacts:
      type: zip
      files:
        - 'HelloWorld.js'